---
- name: Provision Test Server
  hosts: test
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: /path/to/app/Dockerfile
    - name: Pull Docker Image
      docker_image:
        name: myapp
        source: pull
    - name: Run Docker Container
      docker_container:
        name: myapp_container
        image: myapp
        state: started
